# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20161124_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
