# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20161124_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=store.models.file_save_path),
        ),
    ]
