# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20161202_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='no-slug', max_length=200),
            preserve_default=False,
        ),
    ]
