# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='no-slug'),
            preserve_default=False,
        ),
    ]
